/* Generated By:JJTree: Do not edit this line. AST_break.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public class AST_break extends SimpleNode {
    public AST_break(int id) {
        super(id);
    }

    public AST_break(DemoParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public void jjtAccept(DemoParserVisitor visitor, StringBuilder data) {

        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=1129be837b143472c5811bf49bf67186 (do not edit this line) */
