/* Generated By:JJTree: Do not edit this line. ASTexpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public
class ASTexpr extends SimpleNode {
    public ASTexpr(int id) {
        super(id);
    }

    public ASTexpr(DemoParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Integer jjtAccept(DemoParserVisitor visitor, Integer data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=ffd959c55227dcd692062f7e0ddc2688 (do not edit this line) */
