/* Generated By:JJTree: Do not edit this line. ASTprimary.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public
class ASTprimary extends SimpleNode {
    public ASTprimary(int id) {
        super(id);
    }

    public ASTprimary(DemoParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Integer jjtAccept(DemoParserVisitor visitor, Integer data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=75c7356a0ae8c483727f011b57d5cafd (do not edit this line) */
