/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public
class ASTStart extends SimpleNode {
    public ASTStart(int id) {
        super(id);
    }

    public ASTStart(DemoParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Integer jjtAccept(DemoParserVisitor visitor, Integer data) {

        return
                visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=897f0e142696781221a277f5ac3661af (do not edit this line) */
