/* Generated By:JJTree: Do not edit this line. ASTterm.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public class ASTterm extends SimpleNode {
    public ASTterm(int id) {
        super(id);
    }

    public ASTterm(DemoParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Integer jjtAccept(DemoParserVisitor visitor, Integer data) {

        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=c3b918521024c360744ad0a8fa225d4e (do not edit this line) */
