/* Generated By:JJTree: Do not edit this line. ASTtts.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public class ASTtts extends SimpleNode {
    public ASTtts(int id) {
        super(id);
    }

    public ASTtts(DemoParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public void jjtAccept(DemoParserVisitor visitor, StringBuilder data) {

        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=b33ad23ef93aee3cfd01c1db27ddcce9 (do not edit this line) */
