/* Generated By:JJTree: Do not edit this line. ASTwav.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.c1;

public class ASTwav extends SimpleNode {
    public ASTwav(int id) {
        super(id);
    }

    public ASTwav(DemoParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public void jjtAccept(DemoParserVisitor visitor, StringBuilder data) {

        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=15540388a1cf9c0f402f4d15d1fe561e (do not edit this line) */
