/* Generated By:JavaCC: Do not edit this line. DemoParserVisitor.java Version 7.0.13 */
package io.leaderli.c1;

public interface DemoParserVisitor {
    Integer visit(ASTStart node, Integer data);

    Integer visit(ASTexpr node, Integer data);

    Integer visit(ASTterm node, Integer data);

    Integer visit(ASTprimary node, Integer data);

    Integer visit(ASTneg node, Integer data);
}
/* JavaCC - OriginalChecksum=8dcba9cdbed4dc25e44237bdb6ec287d (do not edit this line) */
