/* Generated By:JavaCC: Do not edit this line. DemoParserDefaultVisitor.java Version 7.0.13 */
package io.leaderli.c1;

public class DemoParserDefaultVisitor implements DemoParserVisitor {


    public Integer visit(ASTStart node, Integer data) {
        return node.children[0].jjtAccept(this, null);
    }

    public Integer visit(ASTexpr node, Integer data) {
        Integer left = node.children[0].jjtAccept(this, null);
        Integer right = node.children[1].jjtAccept(this, null);
        String op = (String) node.jjtGetValue();
        if ("+".equals(op)) {
            return left + right;
        } else {
            return left - right;
        }
    }

    public Integer visit(ASTterm node, Integer data) {
        Integer left = node.children[0].jjtAccept(this, null);
        Integer right = node.children[1].jjtAccept(this, null);
        String op = (String) node.jjtGetValue();
        if ("*".equals(op)) {
            return left * right;
        } else {
            return left / right;
        }
    }

    public Integer visit(ASTprimary node, Integer data) {
        return (Integer) node.jjtGetValue();
    }

    public Integer visit(ASTneg node, Integer data) {
        return -node.children[0].jjtAccept(this, null);
    }
}
/* JavaCC - OriginalChecksum=6f22a91cfe32cba788061e89705c44cc (do not edit this line) */
