/* Generated By:JavaCC: Do not edit this line. DemoParserVisitor.java Version 7.0.13 */
package io.leaderli.c1;

public interface DemoParserVisitor {
    public void visit(SimpleNode node, StringBuilder data);

    public void visit(ASTStart node, StringBuilder data);

    public void visit(ASTwav node, StringBuilder data);

    public void visit(ASTtts node, StringBuilder data);

    public void visit(AST_break node, StringBuilder data);
}
/* JavaCC - OriginalChecksum=4995393991de08fd59879bb4a3222985 (do not edit this line) */
