/* Generated By:JavaCC: Do not edit this line. DemoConstants.java */
package io.leaderli.c1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DemoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int B = 2;
  /** RegularExpression Id. */
  int C = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"B\"",
    "\"C\"",
  };

}
