/* Generated By:JavaCC: Do not edit this line. DemoParserTreeConstants.java Version 7.0.13 */
package io.leaderli.c1;

public interface DemoParserTreeConstants {
    public int JJTSTART = 0;
    public int JJTWAV = 1;
    public int JJTVOID = 2;
    public int JJTTTS = 3;
    public int JJT_BREAK = 4;

    public String[] jjtNodeName = { "Start", "wav", "void", "tts", "_break", };
}
/* JavaCC - OriginalChecksum=4a0bc97e9ae22546845f6df8348eacd3 (do not edit this line) */
