/* Generated By:JavaCC: Do not edit this line. DemoParserTreeConstants.java Version 7.0.13 */
package io.leaderli.c1;

public interface DemoParserTreeConstants {
    int JJTSTART = 0;
    int JJTEXPR = 1;
    int JJTTERM = 2;
    int JJTVOID = 3;
    int JJTPRIMARY = 4;
    int JJTNEG = 5;


    String[] jjtNodeName = {
            "Start",
            "expr",
            "term",
            "void",
            "primary",
            "neg",
    };
}
/* JavaCC - OriginalChecksum=40cdea9589e90cbfb35090f4df5d397e (do not edit this line) */
