/* Generated By:JavaCC: Do not edit this line. DemoParserDefaultVisitor.java Version 7.0.13 */
package io.leaderli.c1;

public class DemoParserDefaultVisitor implements DemoParserVisitor {
    public void defaultVisit(SimpleNode node, StringBuilder data) {
        node.childrenAccept(this, data);
        return;
    }

    public void visit(SimpleNode node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTStart node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTwav node, StringBuilder data) {
        data
                .append("\r\n")
                .append("wav:")
                .append(node.jjtGetValue())
                .append("\r\n");
    }

    public void visit(ASTtts node, StringBuilder data) {
        data.append(node.jjtGetValue());
    }

    public void visit(AST_break node, StringBuilder data) {
        data.append("\r\n");
    }
}
/* JavaCC - OriginalChecksum=f216e75ab743c5891ada21645cc01482 (do not edit this line) */
