/* Generated By:JJTree&JavaCC: Do not edit this line. DemoParserConstants.java */
package io.leaderli.c1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DemoParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int EOL = 2;
    /**
     * RegularExpression Id.
     */
    int PLUS = 3;
    /**
     * RegularExpression Id.
     */
    int MINUS = 4;
    /**
     * RegularExpression Id.
     */
    int TIMES = 5;
    /**
     * RegularExpression Id.
     */
    int DIVIDE = 6;
    /**
     * RegularExpression Id.
     */
    int OPEN_PAR = 7;
    /**
     * RegularExpression Id.
     */
    int CLOSE_PAR = 8;
    /**
     * RegularExpression Id.
     */
    int NUMBER = 9;
    /**
     * RegularExpression Id.
     */
    int DIGITS = 10;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "<EOL>",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"/\"",
            "\"(\"",
            "\")\"",
            "<NUMBER>",
            "<DIGITS>",
    };

}
